import type { Promo } from "@blizcc/ui";

export const TEMPLATE_PROMOS: Promo[] = [
  {
    id: "1",
    title: "Tech Jackpot",
    prize: "Earbuds",
    new_price: 100,
    currency: "USD",
    is_default: false,
    original_price: 90,
    max_selections: 1000,
    selection_method: undefined,
    description: "Score a pair of high-quality wireless earbuds worth $30!",
    image_url:
      "https://cdn.shopify.com/s/files/1/2303/2711/files/2_e822dae0-14df-4cb8-b145-ea4dc0966b34.jpg",
  },
  {
    id: "2",
    title: "Fashion Find",
    prize: "$20 Voucher",
    is_default: false,
    new_price: 100,
    max_selections: 100,
    currency: "USD",
    selection_method: undefined,
    original_price: 90,
    description: "Grab a $20 voucher to upgrade your wardrobe.",
    image_url:
      "https://cdn.shopify.com/s/files/1/2303/2711/files/2_e822dae0-14df-4cb8-b145-ea4dc0966b34.jpg",
  },
  {
    id: "3",
    title: "Home Essentials",
    prize: "Desk Lamp",
    is_default: false,
    new_price: 100,
    max_selections: 100,
    currency: "USD",
    selection_method: undefined,
    original_price: 90,
    description: "Brighten your space with a sleek LED lamp, valued at $15.",
    image_url:
      "https://cdn.shopify.com/s/files/1/2303/2711/files/2_e822dae0-14df-4cb8-b145-ea4dc0966b34.jpg",
  },
  {
    id: "4",
    title: "Gadget Bonus",
    prize: "Cable Set",
    is_default: false,
    new_price: 100,
    max_selections: 100,
    selection_method: undefined,
    original_price: 90,
    currency: "USD",
    description:
      "Get a durable 3-in-1 charging cable set for all your devices.",
    image_url:
      "https://cdn.shopify.com/s/files/1/2303/2711/files/2_e822dae0-14df-4cb8-b145-ea4dc0966b34.jpg",
  },
  {
    id: "5",
    title: "Style Steal",
    is_default: false,
    prize: "$10 Gift",
    new_price: 100,
    currency: "USD",
    max_selections: 100,
    selection_method: undefined,
    original_price: 90,
    description: "Enjoy a $10 gift card to shop anything you love.",
    image_url:
      "https://cdn.shopify.com/s/files/1/2303/2711/files/2_e822dae0-14df-4cb8-b145-ea4dc0966b34.jpg",
  },
  {
    id: "6",
    title: "Kitchen Win",
    is_default: false,
    prize: "Blender",
    new_price: 100,
    max_selections: 100,
    selection_method: undefined,
    original_price: 90,
    currency: "USD",
    description: "Blend on the go with this compact $12 blender.",
    image_url:
      "https://cdn.shopify.com/s/files/1/2303/2711/files/2_e822dae0-14df-4cb8-b145-ea4dc0966b34.jpg",
  },
  {
    id: "7",
    title: "Daily Deal",
    is_default: false,
    prize: "$5 Coupon",
    max_selections: 100,
    new_price: 100,
    currency: "USD",
    original_price: 90,
    description: "Save $5 on your next Temu haul!",
    image_url:
      "https://cdn.shopify.com/s/files/1/2303/2711/files/2_e822dae0-14df-4cb8-b145-ea4dc0966b34.jpg",
  },
  {
    id: "8",
    title: "Better Luck Next Time!",
    prize: "No Prize This Time",
    is_default: true,
    new_price: 0,
    currency: "USD",
    selection_method: undefined,
    original_price: 0,
    description:
      "Thanks for playing! Unfortunately, you didn't win a prize this round. Try again for another chance!",
    image_url: "",
  },
];
